// One-off: link Sooraj's (AC-CUST-00245) unlinked advance payment to his
// backfilled September invoice.
//
// Context: PAY-00286 (AED 240, bank_transfer, ref WIOBANK, dated 2026-08-31)
// was recorded as an advance payment (is_advance: true, invoice_id: null)
// the day before his subscription cycle started, since no invoice existed
// yet to attach it to. AC-INV-01567 (Sep 1 - Sep 30 cycle, AED 240) was
// later generated by the prepaid catch-up backfill and has sat as 'issued'
// (unpaid) ever since, because reconcileInvoicePaymentStatus only counts
// payments actually linked via invoice_id — this advance payment was never
// linked. The amount matches exactly and the payment predates the invoice
// by one day (a normal prepay-before-invoicing sequence), so it's the
// obvious match.
//
// This script:
//   1. Sets PAY-00286.invoice_id to AC-INV-01567's id.
//   2. Re-runs reconcileInvoicePaymentStatus for AC-INV-01567 so its status
//      flips from 'issued' to 'paid'.
//
// Dry-run by default (shows current state, no writes). Pass --confirm to apply.
//
// Usage:
//   npx tsx scripts/link-sooraj-advance-payment.ts            (dry run)
//   npx tsx scripts/link-sooraj-advance-payment.ts --confirm   (apply)

import fs from 'fs'
for (const line of fs.readFileSync('.env.local', 'utf8').split('\n')) {
  const m = line.match(/^([^#=]+)=(.*)$/)
  if (m) process.env[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '')
}

import { createClient } from '@supabase/supabase-js'
import { reconcileInvoicePaymentStatus } from '../lib/invoices/reconcile'

const CONFIRM = process.argv.includes('--confirm')
const CUSTOMER_ID  = '6204e548-edda-43d7-8e17-5088e2c81f50' // Sooraj, AC-CUST-00245
const INVOICE_ID   = '82e1bf08-d14d-4c37-a539-9a8bfd3d6276' // AC-INV-01567
const PAYMENT_ID   = '099df40b-6559-4593-87ca-a53e5b248a68' // PAY-00286

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const admin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } },
) as any

async function snapshot() {
  const { data: invoice } = await admin
    .from('invoices')
    .select('invoice_number, billing_period_start, billing_period_end, total_amount, status')
    .eq('id', INVOICE_ID)
    .single()
  console.log('invoice:', invoice)

  const { data: payment } = await admin
    .from('payments')
    .select('payment_number, amount, invoice_id, payment_date, mode, reference_number, is_advance')
    .eq('id', PAYMENT_ID)
    .single()
  console.log('payment:', payment)
}

async function main() {
  console.log('--- BEFORE ---')
  await snapshot()

  if (!CONFIRM) {
    console.log(`
[DRY RUN] plan:
  1. PAY-00286.invoice_id -> ${INVOICE_ID} (AC-INV-01567)
  2. reconcileInvoicePaymentStatus(AC-INV-01567) -> expected 'issued' -> 'paid' (240 paid / 240 total)

No writes made. Re-run with --confirm to apply.`)
    return
  }

  const { error: linkErr } = await admin
    .from('payments')
    .update({ invoice_id: INVOICE_ID })
    .eq('id', PAYMENT_ID)
  if (linkErr) { console.error('failed to link payment:', linkErr.message); process.exit(1) }

  await reconcileInvoicePaymentStatus(admin, INVOICE_ID)

  console.log('\n--- AFTER ---')
  await snapshot()
}

main().catch(e => { console.error(e); process.exit(1) })
